# -*- coding: utf-8 -*-
"""Monthly Budget Planner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzmMh0upZRQf2OsxCW_1ulRUI2GJCwgP
"""

import json
import os


DATA_FILE = "monthly_budget_data.json"

def load_data():

    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError:

            print("Warning: Data file corrupted or empty. Starting fresh.")
            return {"income": 0.0, "expenses": []}
    else:

        return {"income": 0.0, "expenses": []}

def save_data(data):

    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=4)

def set_income(data):

    while True:
        try:
            amount = float(input("Enter your total monthly income (e.g., 4500.00): $"))
            if amount < 0:
                print("Income cannot be negative. Please try again.")
                continue
            data["income"] = amount
            save_data(data)
            print(f"\n✅ Monthly income set to ${amount:,.2f}.")
            break
        except ValueError:
            print("Invalid input. Please enter a numerical value.")

def add_expense(data):

    category = input("Enter expense category (e.g., Groceries, Rent, Entertainment): ").strip()
    description = input("Enter a brief description (e.g., Monthly apartment rent): ").strip()

    while True:
        try:
            amount = float(input(f"Enter amount for {category}: $"))
            if amount <= 0:
                print("Expense amount must be positive. Please try again.")
                continue

            # Create the expense object
            expense = {
                "category": category,
                "description": description,
                "amount": amount
            }

            data["expenses"].append(expense)
            save_data(data)
            print(f"\n✅ Expense '{description}' (${amount:,.2f}) added successfully.")
            break
        except ValueError:
            print("Invalid input for amount. Please enter a numerical value.")

def view_summary(data):


    total_expenses = sum(expense["amount"] for expense in data["expenses"])
    remaining_balance = data["income"] - total_expenses

    print("-" * 40)
    print("         💰 MONTHLY BUDGET SUMMARY 💰")
    print("-" * 40)
    print(f"Total Monthly Income:    ${data['income']:>10,.2f}")
    print(f"Total Expenses Tracked:  ${total_expenses:>10,.2f}")
    print("-" * 40)

    # Print balance with appropriate color/signage
    if remaining_balance >= 0:
        print(f"💰 Remaining Budget:     ${remaining_balance:>10,.2f}")
    else:
        print(f"🚨 Budget Overdrawn By: ${abs(remaining_balance):>10,.2f}")

    print("-" * 40)
    print("\n--- Detailed Expense Breakdown ---")
    if not data["expenses"]:
        print("No expenses recorded yet.")
        return


    category_totals = {}
    for expense in data["expenses"]:
        category = expense["category"]
        amount = expense["amount"]
        category_totals[category] = category_totals.get(category, 0) + amount

    for category, total in category_totals.items():
        percentage = (total / data["income"]) * 100 if data["income"] > 0 else 0
        print(f"- {category:<20}: ${total:8,.2f} ({percentage:.1f}%)")

    print("-" * 40)


def main():

    budget_data = load_data()


    if budget_data["income"] == 0.0:
        print("Welcome to the Monthly Budget Planner!")
        print("Let's start by setting your monthly income.")
        set_income(budget_data)

    while True:
        print("\n" + "=" * 40)
        print("      💵 BUDGET PLANNER MENU 💵")
        print("=" * 40)
        print("1. Set/Update Monthly Income")
        print("2. Add New Expense")
        print("3. View Summary (Balance & Breakdown)")
        print("4. Exit and Save")
        print("=" * 40)

        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            set_income(budget_data)
        elif choice == '2':
            add_expense(budget_data)
        elif choice == '3':
            view_summary(budget_data)
        elif choice == '4':
            save_data(budget_data)
            print("\nGoodbye! Your budget data has been saved to monthly_budget_data.json.")
            break
        else:
            print("\n❌ Invalid choice. Please enter a number between 1 and 4.")

if __name__ == "__main__":
    main()